// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeCadastro.Domain.SistemaCadastroContext;

#nullable disable

namespace SistemaDeCadastro.Domain.Migrations
{
    [DbContext(typeof(SistemaDeCadastroContext))]
    [Migration("20260706224309_InitialCreateMySqlComBloodType")]
    partial class InitialCreateMySqlComBloodType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_log");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("data_hora");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_acesso");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("log_acesso", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_agendamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_atendimento");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("data_hora");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("responsavel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.AvailablePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_permissao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modulo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_permissao");

                    b.HasKey("Id");

                    b.ToTable("permissoes_disponiveis", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.BloodType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_blood_type");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("blood_types", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.CareService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_atendimento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_agendamento");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    b.Property<string>("Referral")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encaminhamento");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("data_atendimento");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("atendimentos", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.ClinicalCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_condicao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_condicao");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("condicoesclinicas", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_departamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_departamento");

                    b.HasKey("Id");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_funcionario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cpf");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cargo");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Illness", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_doenca");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("doencas", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_conta_login");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("ultimo_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("contas_login", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Medicine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_medicamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdministrationRoute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("via_administracao");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dosagem");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("medicamentos", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.MedicinePatientClinicalCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_medicamento_acond");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("frequencia");

                    b.Property<long>("MedicineId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_medicamento");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<long>("PatientClinicalConditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido_condicao");

                    b.Property<string>("PrescribedDosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dosagem_prescrita");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientClinicalConditionId");

                    b.ToTable("medicamento_acolhido_condicaoclinica", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<long?>("BloodTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_blood_type");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("documento");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sexo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("acolhidos", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientClinicalCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido_condicao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClinicalConditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_condicao");

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("date")
                        .HasColumnName("data_diagnostico");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalConditionId");

                    b.HasIndex("PatientId");

                    b.ToTable("acolhido_condicaoclinica", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientEmployee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido_funcionario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_funcionario");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    b.Property<string>("ResponsibilityFunction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("funcao_responsavel");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PatientId");

                    b.ToTable("acolhido_funcionario", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientIllness", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido_doenca");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DiagnosisDate")
                        .HasColumnType("date")
                        .HasColumnName("data_diagnostico");

                    b.Property<long>("IllnessId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_doenca");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    b.HasKey("Id");

                    b.HasIndex("IllnessId");

                    b.HasIndex("PatientId");

                    b.ToTable("acolhido_doenca", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pagamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_agendamento");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id_transacao_externa");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("metodo_pagamento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_total");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Responsible", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_responsavel");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_acolhido");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("parentesco");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("responsaveis", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.UserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario_permissao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("data_concessao");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_permissao");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("usuarios_permissoes", (string)null);
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.AccessLog", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Appointment", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.CareService", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Appointment", "Appointment")
                        .WithMany("CareServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Patient", "Patient")
                        .WithMany("CareServices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", "User")
                        .WithMany("CareServices")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Employee", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.MedicinePatientClinicalCondition", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Medicine", "Medicine")
                        .WithMany("PatientClinicalConditionMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.PatientClinicalCondition", "PatientClinicalCondition")
                        .WithMany("Medicines")
                        .HasForeignKey("PatientClinicalConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PatientClinicalCondition");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Patient", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.BloodType", "BloodType")
                        .WithMany("Patients")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientClinicalCondition", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.ClinicalCondition", "ClinicalCondition")
                        .WithMany("PatientClinicalConditions")
                        .HasForeignKey("ClinicalConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Patient", "Patient")
                        .WithMany("PatientClinicalConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicalCondition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientEmployee", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Employee", "Employee")
                        .WithMany("PatientEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Patient", "Patient")
                        .WithMany("PatientEmployees")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientIllness", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Illness", "Illness")
                        .WithMany("PatientIllnesses")
                        .HasForeignKey("IllnessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Patient", "Patient")
                        .WithMany("PatientIllnesses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Illness");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Payment", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Appointment", "Appointment")
                        .WithMany("Payments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Responsible", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.Patient", "Patient")
                        .WithMany("Responsibles")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.UserPermission", b =>
                {
                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.AvailablePermission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Appointment", b =>
                {
                    b.Navigation("CareServices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.AvailablePermission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.BloodType", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.ClinicalCondition", b =>
                {
                    b.Navigation("PatientClinicalConditions");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Employee", b =>
                {
                    b.Navigation("PatientEmployees");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Illness", b =>
                {
                    b.Navigation("PatientIllnesses");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.LoginAccount", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Appointments");

                    b.Navigation("CareServices");

                    b.Navigation("Payments");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Medicine", b =>
                {
                    b.Navigation("PatientClinicalConditionMedicines");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CareServices");

                    b.Navigation("PatientClinicalConditions");

                    b.Navigation("PatientEmployees");

                    b.Navigation("PatientIllnesses");

                    b.Navigation("Responsibles");
                });

            modelBuilder.Entity("SistemaDeCadastro.Domain.Models.Stage.PatientClinicalCondition", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
